CHANGELOG.md
README.md
composer.json
composer.lock
phpstan.neon
src/Classes/AbstractOrFinalRule.php
test/AutoReview/TestCodeTest.php
test/Integration/Classes/AbstractOrFinalRuleTest.php
test/Integration/Classes/Fixture/AbstractClass.php
test/Integration/Classes/Fixture/AbstractClassWithAnonymousClass.php
test/Integration/Classes/Fixture/ExampleInterface.php
test/Integration/Classes/Fixture/ExampleTrait.php
test/Integration/Classes/Fixture/FinalClass.php
test/Integration/Classes/Fixture/FinalClassWithAnonymousClass.php
test/Integration/Classes/Fixture/NeitherAbstractNorFinalClass.php
test/Integration/Classes/Fixture/TraitWithAnonymousClass.php
test/Integration/Classes/Fixture/script-with-anonymous-class.php
test/Unit/Classes/AbstractOrFinalRuleTest.php

This PR
Related to https://twitter.com/localheinz/status/1062284076680470529.
/cc @matthiasnoback @ondrejmirtes

Enhancement: Implement AbstractOrFinalRule

---

README.md

Fix: Class name in README.md

---

CHANGELOG.md
README.md
src/Classes/FinalRule.php
test/Integration/Classes/FinalRuleTest.php
test/Unit/Classes/FinalRuleTest.php

Enhancement: Implement FinalRule

---

test/AutoReview/SrcCodeTest.php

Fix: Remove test asserting that source classes are abstract or final

---

README.md

Fix: Suggest to install library as development dependency

---

test/Integration/Classes/AbstractOrFinalRuleTest.php
test/Integration/Classes/FinalRuleTest.php

Fix: Use data providers in tests

---

test/Unit/Classes/AbstractOrFinalRuleTest.php
test/Unit/Classes/FinalRuleTest.php

Fix: Test method names

---

CHANGELOG.md

Fix: Links

---

.travis.yml
CHANGELOG.md
Makefile
README.md
phpstan.neon
src/Functions/NoNullableReturnTypeDeclarationRule.php
src/Methods/NoNullableReturnTypeDeclarationRule.php
test/Fixture/Functions/NoNullableReturnTypeDeclaration/anonymous-function-in-script-with-nullable-return-type-declaration.php
test/Fixture/Functions/NoNullableReturnTypeDeclaration/anonymous-function-in-script-with-return-type-declaration.php
test/Fixture/Functions/NoNullableReturnTypeDeclaration/anonymous-function-in-script-without-return-type-declaration.php
test/Fixture/Functions/NoNullableReturnTypeDeclaration/named-function-in-script-with-nullable-return-type-declaration.php
test/Fixture/Functions/NoNullableReturnTypeDeclaration/named-function-in-script-with-return-type-declaration.php
test/Fixture/Functions/NoNullableReturnTypeDeclaration/named-function-in-script-without-return-type-declaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInAnonymousClassWithNullableReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInAnonymousClassWithReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInAnonymousClassWithoutReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInClassWithNullableReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInClassWithReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInClassWithoutReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInInterfaceWithNullableReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInInterfaceWithReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInInterfaceWithoutReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInTraitWithNullableReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInTraitWithReturnTypeDeclaration.php
test/Fixture/Methods/NoNullableReturnTypeDeclaration/MethodInTraitWithoutReturnTypeDeclaration.php
test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php

Enhancement: Implement NoNullableReturnTypeDeclarationRule

---

src/Classes/FinalRule.php

Fix: Add space between parameter type and name

---

.php_cs.fixture
.travis.yml
CHANGELOG.md
Makefile
README.md
src/Closures/NoParameterWithNullDefaultValueRule.php
test/Fixture/Closures/NoParameterWithNullDefaultValueRule/Failure/closure-with-parameter-with-null-default-value.php
test/Fixture/Closures/NoParameterWithNullDefaultValueRule/Failure/closure-with-parameter-with-root-namespace-referenced-null-default-value.php
test/Fixture/Closures/NoParameterWithNullDefaultValueRule/Failure/closure-with-parameter-with-wrongly-capitalized-null-default-value.php
test/Fixture/Closures/NoParameterWithNullDefaultValueRule/Success/closure-with-parameter-with-non-null-default-value.php
test/Fixture/Closures/NoParameterWithNullDefaultValueRule/Success/closure-with-parameter-without-default-value.php
test/Fixture/Closures/NoParameterWithNullDefaultValueRule/Success/closure-without-parameters.php
test/Integration/Closures/NoParameterWithNullDefaultValueRuleTest.php

Enhancement: Implement Closures\NoParameterWithNullDefaultValueRule

---

.travis.yml
CHANGELOG.md
Makefile
README.md
phpstan.neon
src/Functions/NoParameterWithNullDefaultValueRule.php
test/Fixture/Functions/NoParameterWithNullDefaultValueRule/Failure/function-with-parameter-with-null-default-value.php
test/Fixture/Functions/NoParameterWithNullDefaultValueRule/Failure/function-with-parameter-with-root-namespace-referenced-null-default-value.php
test/Fixture/Functions/NoParameterWithNullDefaultValueRule/Failure/function-with-parameter-with-wrongly-capitalized-null-default-value.php
test/Fixture/Functions/NoParameterWithNullDefaultValueRule/Success/function-with-parameter-with-non-null-default-value.php
test/Fixture/Functions/NoParameterWithNullDefaultValueRule/Success/function-with-parameter-without-default-value.php
test/Fixture/Functions/NoParameterWithNullDefaultValueRule/Success/function-without-parameters.php
test/Integration/Functions/NoParameterWithNullDefaultValueRuleTest.php

Enhancement: Implement Functions\NoParameterWithNullDefaultValueRule

---

CHANGELOG.md
README.md
phpstan.neon
src/Closures/NoParameterWithNullableTypeDeclarationRule.php
test/Fixture/Closures/NoParameterWithNullableTypeDeclarationRule/Failure/closure-with-parameter-with-nullable-type-declaration.php
test/Fixture/Closures/NoParameterWithNullableTypeDeclarationRule/Success/closure-with-parameter-with-type-declaration.php
test/Fixture/Closures/NoParameterWithNullableTypeDeclarationRule/Success/closure-with-parameter-without-type-declaration.php
test/Fixture/Closures/NoParameterWithNullableTypeDeclarationRule/Success/closure-without-parameters.php
test/Integration/Closures/NoParameterWithNullableTypeDeclarationRuleTest.php

Enhancement: Implement Closures\NoParameterWithNullableTypeDeclarationRule

---

.travis.yml
CHANGELOG.md
Makefile
README.md
phpstan.neon
src/Functions/NoParameterWithNullableTypeDeclarationRule.php
test/Fixture/Functions/NoParameterWithNullableTypeDeclarationRule/Failure/function-with-parameter-with-nullable-type-declaration.php
test/Fixture/Functions/NoParameterWithNullableTypeDeclarationRule/Success/function-with-parameter-with-type-declaration.php
test/Fixture/Functions/NoParameterWithNullableTypeDeclarationRule/Success/function-with-parameter-without-type-declaration.php
test/Fixture/Functions/NoParameterWithNullableTypeDeclarationRule/Success/function-without-parameters.php
test/Integration/Functions/NoParameterWithNullableTypeDeclarationRuleTest.php

Enhancement: Implement Functions\NoParameterWithNullableTypeDeclarationRule

---

CHANGELOG.md
README.md
phpstan.neon
src/Methods/NoParameterWithNullableTypeDeclarationRule.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Failure/MethodInClassWithParameterWithNullableTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Failure/MethodInInterfaceWithParameterWithNullableTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Failure/method-in-anonymous-class-with-parameter-with-nullable-type-declaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInClassWithParameterWithTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInClassWithParameterWithoutTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInClassWithoutParameters.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInInterfaceWithParameterWithTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInInterfaceWithParameterWithoutTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInInterfaceWithoutParameters.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInTraitWithParameterWithNullableTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInTraitWithParameterWithTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInTraitWithParameterWithoutTypeDeclaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/MethodInTraitWithoutParameters.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/method-in-anonymous-class-with-parameter-with-type-declaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/method-in-anonymous-class-with-parameter-without-type-declaration.php
test/Fixture/Methods/NoParameterWithNullableTypeDeclarationRule/Success/method-in-anonymous-class-without-parameters.php
test/Integration/Methods/NoParameterWithNullableTypeDeclarationRuleTest.php

Enhancement: Implement Methods\NoParameterWithNullableTypeDeclarationRule

---

CHANGELOG.md
README.md

Fix: Wording

---

CHANGELOG.md
README.md
phpstan.neon
rules.neon

Enhancement: Extract rules.neon

---

CHANGELOG.md

Fix: Do not bother with wrapping content in CHANGELOG.md

---

CHANGELOG.md

Fix: Start items with upper-case

---

.php_cs.fixture
CHANGELOG.md
README.md
phpstan.neon
rules.neon
src/Methods/NoConstructorParameterWithDefaultValueRule.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Failure/ConstructorInClassWithParameterWithDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Failure/ConstructorWithWrongCapitalizationInClassWithParameterWithDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Failure/constructor-in-anonymous-class-with-parameter-with-default-value.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Failure/constructor-with-wrong-capitalization-in-anonymous-class-with-parameter-with-default-value.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/ConstructorInClassWithParameterWithoutDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/ConstructorInClassWithoutParameters.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/ConstructorInTraitWithParameterWithDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/ConstructorInTraitWithParameterWithoutDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/ConstructorInTraitWithoutParameters.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/MethodInClassWithParameterWithDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/MethodInTraitWithParameterWithDefaultValue.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/constructor-in-anonymous-class-with-parameter-without-default-value.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/constructor-in-anonymous-class-without-parameters.php
test/Fixture/Methods/NoConstructorParameterWithDefaultValueRule/Success/method-in-anonymous-class-with-parameter-with-default-value.php
test/Integration/Methods/NoConstructorParameterWithDefaultValueRuleTest.php

Enhancement: Implement NoConstructorParameterWithDefaultValueRule

---

README.md

Fix: Adjust README.md in regard to AbstractOrFinalRule and FinalRule

---

.travis.yml
Makefile
phpstan.neon

Fix: Configure rules via phpstan.neon instead of --level option

---

.travis.yml
Makefile
phpstan.neon

Enhancement: Also run phpstan against tests

---

test/AutoReview/TestCodeTest.php

This PR
💁‍♂️ This is handled by `Classes\FinalRule`.

Fix: Remove test asserting that test classes are abstract or final

---

.travis.yml
CHANGELOG.md
Makefile
phpstan.neon
src/Classes/FinalRule.php

This PR
Follows #45.
Follows #51.

Fix: Remove default values from constructor parameters of Classes\FinalRule

---

composer.json
composer.lock
phpstan.neon

Enhancement: Require phpstan/phpstan-deprecation-rules

---

.editorconfig
.github/CONTRIBUTING.md
.travis.yml
Makefile
README.md

Enhancement: Synchronize project tooling configuration with localheinz/repository

---

.travis.yml
CHANGELOG.md
Makefile
README.md
phpstan.neon
rules.neon
src/Classes/NoExtendsRule.php
test/Fixture/Classes/NoExtendsRule/Failure/ClassExtendingOtherClass.php
test/Fixture/Classes/NoExtendsRule/Failure/OtherClass.php
test/Fixture/Classes/NoExtendsRule/Failure/anonymous-class-extending-other-class.php
test/Fixture/Classes/NoExtendsRule/Success/ExampleClass.php
test/Fixture/Classes/NoExtendsRule/Success/ExampleInterface.php
test/Fixture/Classes/NoExtendsRule/Success/InterfaceExtendingOtherInterface.php
test/Fixture/Classes/NoExtendsRule/Success/OtherInterface.php
test/Fixture/Classes/NoExtendsRule/Success/anonymous-class.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Failure/ClassExtendingOtherClass.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Failure/OtherClass.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Failure/anonymous-class-extending-other-class.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/ClassAllowedToBeExtended.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/ClassExtendingClassAllowedToBeExtended.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/ExampleClass.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/ExampleInterface.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/InterfaceExtendingOtherInterface.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/OtherInterface.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/anonymous-class-extending-class-allowed-to-be-extended.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/anonymous-class.php
test/Integration/Classes/NoExtendsRuleTest.php
test/Integration/Classes/NoExtendsRuleWithClassesAllowedToBeExtendedTest.php

Enhancement: Implement Classes\NoExtendsRule

---

README.md

Fix: Wording in README.md

---

CHANGELOG.md
README.md
phpstan.neon
src/Classes/NoExtendsRule.php
test/Fixture/Classes/NoExtendsRule/Success/ClassExtendingPhpUnitFrameworkTestCase.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/ClassExtendingPhpUnitFrameworkTestCase.php
test/Integration/Classes/NoExtendsRuleTest.php
test/Integration/Classes/NoExtendsRuleWithClassesAllowedToBeExtendedTest.php

Enhancement: Adjust Classes\NoExtendsRule to allow to extend from a set of classes by default

---

test/Integration/AbstractTestCase.php

Remove word 'Test' from testTestsAnalysisSucceeds to make the method's name similar to testAnalysisFails

Remove word 'Test' from testTestsAnalysisSucceeds

---

README.md

Link phpstan/phpstan-deprecation-rules to https://github.com/phpstan/phpstan-deprecation-rules instead of https://github.com/phpstan/phpstan

Fix phpstan/phpstan-deprecation-rules link

---

.php_cs.fixture
CHANGELOG.md
README.md
src/Expressions/NoIssetRule.php
test/Fixture/Expressions/NoIssetRule/Failure/isset-used-with-correct-case.php
test/Fixture/Expressions/NoIssetRule/Failure/isset-used-with-incorrect-case.php
test/Fixture/Expressions/NoIssetRule/Success/isset-not-used.php
test/Integration/Expressions/NoIssetRuleTest.php

Enhancement: Implement Expressions\NoIssetRule

---

composer.json
composer.lock
test/AutoReview/SrcCodeTest.php
test/AutoReview/TestCodeTest.php
test/Fixture/Classes/NoExtendsRule/Success/ClassExtendingPhpUnitFrameworkTestCase.php
test/Fixture/Classes/NoExtendsRuleWithClassesAllowedToBeExtended/Success/ClassExtendingPhpUnitFrameworkTestCase.php
test/Integration/Classes/FinalRuleTest.php
test/Integration/Classes/FinalRuleWithAbstractClassesAllowedTest.php
test/Integration/Classes/FinalRuleWithExcludedClassNamesTest.php
test/Integration/Classes/NoExtendsRuleTest.php
test/Integration/Classes/NoExtendsRuleWithClassesAllowedToBeExtendedTest.php
test/Integration/Closures/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Closures/NoParameterWithNullDefaultValueRuleTest.php
test/Integration/Closures/NoParameterWithNullableTypeDeclarationRuleTest.php
test/Integration/Expressions/NoIssetRuleTest.php
test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Functions/NoParameterWithNullDefaultValueRuleTest.php
test/Integration/Functions/NoParameterWithNullableTypeDeclarationRuleTest.php
test/Integration/Methods/NoConstructorParameterWithDefaultValueRuleTest.php
test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Methods/NoParameterWithNullDefaultValueRuleTest.php
test/Integration/Methods/NoParameterWithNullableTypeDeclarationRuleTest.php

This PR
💁‍♂ For reference, see https://github.com/localheinz/php-cs-fixer-config/compare/1.19.0...1.20.0.

Enhancement: Update localheinz/php-cs-fixer-config

---

CHANGELOG.md
phpstan.neon
rules.neon

Fix: Enable Expressions\NoIssetRule

---

CHANGELOG.md
README.md
src/Classes/FinalRule.php
test/Fixture/Classes/FinalRule/Failure/NonFinalClassWithoutEntityAnnotationInInlineDocBlock.php
test/Fixture/Classes/FinalRule/Failure/NonFinalClassWithoutEntityAnnotationInMultilineDocBlock.php
test/Fixture/Classes/FinalRule/Failure/NonFinalClassWithoutOrmEntityAnnotationInInlineDocBlock.php
test/Fixture/Classes/FinalRule/Failure/NonFinalClassWithoutOrmEntityAnnotationInMultilineDocBlock.php
test/Fixture/Classes/FinalRule/Success/NonFinalClassWithEntityAnnotationInInlineDocBlock.php
test/Fixture/Classes/FinalRule/Success/NonFinalClassWithEntityAnnotationInMultilineDocBlock.php
test/Fixture/Classes/FinalRule/Success/NonFinalClassWithOrmEntityAnnotationInInlineDocBlock.php
test/Fixture/Classes/FinalRule/Success/NonFinalClassWithOrmEntityAnnotationInMultilineDocBlock.php
test/Integration/Classes/FinalRuleTest.php

This PR
Fixes #78.
💁‍♂ Inspired by the work on [`PhpCsFixer\Fixer\ClassNotation\FinalClassFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.15/src/Fixer/ClassNotation/FinalClassFixer.php) and [`PhpCsFixer\Fixer\ClassNotation\FinalInternalClassFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.15/src/Fixer/ClassNotation/FinalInternalClassFixer.php), contributed by @keradus, @Slamdunk, and @Spacepossum for [`friendsofphp/php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

Enhancement: Adjust Classes\FinalRule to ignore Doctrine entities

---

test/Integration/AbstractTestCase.php
test/Integration/Classes/FinalRuleTest.php
test/Integration/Classes/FinalRuleWithAbstractClassesAllowedTest.php
test/Integration/Classes/FinalRuleWithExcludedClassNamesTest.php
test/Integration/Classes/NoExtendsRuleTest.php
test/Integration/Classes/NoExtendsRuleWithClassesAllowedToBeExtendedTest.php
test/Integration/Closures/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Closures/NoParameterWithNullDefaultValueRuleTest.php
test/Integration/Closures/NoParameterWithNullableTypeDeclarationRuleTest.php
test/Integration/Expressions/NoIssetRuleTest.php
test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Functions/NoParameterWithNullDefaultValueRuleTest.php
test/Integration/Functions/NoParameterWithNullableTypeDeclarationRuleTest.php
test/Integration/Methods/NoConstructorParameterWithDefaultValueRuleTest.php
test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Methods/NoParameterWithNullDefaultValueRuleTest.php
test/Integration/Methods/NoParameterWithNullableTypeDeclarationRuleTest.php

Fix: Replace Generator return type declaration with less specific iterable

---

.travis.yml
CHANGELOG.md
Makefile
composer.json
composer.lock
src/Classes/FinalRule.php
src/Classes/NoExtendsRule.php
src/Closures/NoNullableReturnTypeDeclarationRule.php
src/Closures/NoParameterWithNullDefaultValueRule.php
src/Closures/NoParameterWithNullableTypeDeclarationRule.php
src/Functions/NoNullableReturnTypeDeclarationRule.php
src/Functions/NoParameterWithNullDefaultValueRule.php
src/Functions/NoParameterWithNullableTypeDeclarationRule.php
src/Methods/NoConstructorParameterWithDefaultValueRule.php
src/Methods/NoNullableReturnTypeDeclarationRule.php
src/Methods/NoParameterWithNullDefaultValueRule.php
src/Methods/NoParameterWithNullableTypeDeclarationRule.php

Enhancement: Require at least phpstan/phpstan:~0.11.7

---

CHANGELOG.md
phpstan.neon
rules.neon

Fix: Add missing parametersSchema configuration

---

phpstan.neon
src/Classes/FinalRule.php
src/Classes/NoExtendsRule.php

Enhancement: Infer private property type from constructor

---

.travis.yml

Enhancement: Run infection on PHP 7.3

---

CHANGELOG.md
README.md
rules.neon
src/Expressions/NoEmptyRule.php
test/Fixture/Expressions/NoEmptyRule/Failure/empty-used-with-correct-case.php
test/Fixture/Expressions/NoEmptyRule/Failure/empty-used-with-incorrect-case.php
test/Fixture/Expressions/NoEmptyRule/Success/empty-not-used.php
test/Integration/Expressions/NoEmptyRuleTest.php

Enhancement: Implement Expressions\NoEmptyRule

---

README.md

Enhancement: Add link for isset()

---

CHANGELOG.md
README.md
rules.neon
src/Expressions/NoEvalRule.php
test/Fixture/Expressions/NoEvalRule/Failure/eval-used-with-correct-case.php
test/Fixture/Expressions/NoEvalRule/Failure/eval-used-with-incorrect-case.php
test/Fixture/Expressions/NoEvalRule/Success/eval-not-used.php
test/Integration/Expressions/NoEvalRuleTest.php

Enhancement: Implement Expressions\NoEvalRule

---

.php_cs.fixture
CHANGELOG.md
README.md
rules.neon
src/Expressions/NoErrorSuppressionRule.php
test/Fixture/Expressions/NoErrorSuppressionRule/Failure/error-suppression-used.php
test/Fixture/Expressions/NoErrorSuppressionRule/Success/error-suppression-not-used.php
test/Integration/Expressions/NoErrorSuppressionRuleTest.php

Enhancement: Implement Expressions\NoErrorSuppressionRule

---

CHANGELOG.md

Fix: Link in CHANGELOG.md

---

.travis.yml
CHANGELOG.md
Makefile
README.md
rules.neon
src/Expressions/NoCompactRule.php
test/Fixture/Expressions/NoCompactRule/Failure/compact-used-with-alias.php
test/Fixture/Expressions/NoCompactRule/Failure/compact-used-with-correct-case.php
test/Fixture/Expressions/NoCompactRule/Failure/compact-used-with-incorrect-case.php
test/Fixture/Expressions/NoCompactRule/Success/compact-not-used.php
test/Integration/Expressions/NoCompactRuleTest.php

Enhancement: Implement Expressions\NoCompactRule

---

CHANGELOG.md
README.md
rules.neon
src/Statements/NoSwitchRule.php
test/Fixture/Statements/NoSwitchRule/Failure/switch-used-with-correct-case.php
test/Fixture/Statements/NoSwitchRule/Failure/switch-used-with-incorrect-case.php
test/Fixture/Statements/NoSwitchRule/Success/switch-not-used.php
test/Integration/Statements/NoSwitchRuleTest.php

Enhancement: Implement Statements\NoSwitchRule

---

CHANGELOG.md
README.md
composer.json
composer.lock
rules.neon
src/Methods/NoParameterWithContainerTypeDeclarationRule.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/ClassImplementingContainerInterface.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/ClassWithMethodWithParameterWithClassImplementingContainerInterfaceAsTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/ClassWithMethodWithParameterWithContainerInterfaceAsTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/ClassWithMethodWithParameterWithInterfaceExtendingContainerInterfaceAsTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/ClassWithMethodWithParameterWithServiceLocatorInterfaceAsTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/InterfaceExtendingContainerInterface.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/InterfaceWithMethodWithParameterWithContainerInterfaceAsTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/InterfaceWithMethodWithParameterWithServiceLocatorInterfaceAsTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/anonymous-class-with-method-with-parameter-with-class-implementing-container-interface-as-type-declaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/anonymous-class-with-method-with-parameter-with-container-interface-as-type-declaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/anonymous-class-with-method-with-parameter-with-interface-extending-container-interface-as-type-declaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/anonymous-class-with-method-with-parameter-with-service-locator-interface-as-type-declaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/ClassWithMethodWithParameterWithOtherTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/ClassWithMethodWithoutParameter.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/ContainerInterface.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/InterfaceWithMethodWithParameterWithOtherTypeDeclaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/InterfaceWithMethodWithoutParameter.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/anonymous-class-with-method-with-parameter-with-other-type-declaration.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/anonymous-class-with-method-without-parameter.php
test/Integration/Methods/NoParameterWithContainerTypeDeclarationRuleTest.php

Enhancement: Implement Methods\NoParameterWithContainerTypeDeclarationRule

---

CHANGELOG.md
README.md
rules.neon
src/Methods/FinalInAbstractClassRule.php
test/Fixture/Methods/FinalInAbstractClassRule/Failure/AbstractClassWithProtectedMethod.php
test/Fixture/Methods/FinalInAbstractClassRule/Failure/AbstractClassWithPublicMethod.php
test/Fixture/Methods/FinalInAbstractClassRule/Success/AbstractClassWithAbstractMethod.php
test/Fixture/Methods/FinalInAbstractClassRule/Success/AbstractClassWithFinalProtectedMethod.php
test/Fixture/Methods/FinalInAbstractClassRule/Success/AbstractClassWithFinalPublicMethod.php
test/Fixture/Methods/FinalInAbstractClassRule/Success/AbstractClassWithPrivateMethod.php
test/Integration/AbstractTestCase.php
test/Integration/Methods/FinalInAbstractClassRuleTest.php

Enhancement: Implement Methods\FinalInAbstractClassRule

---

README.md

Fix: Add missing section heading

---

CHANGELOG.md
src/Methods/NoParameterWithContainerTypeDeclarationRule.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Failure/ClassImplementingContainerInterfaceWithMethodWithParameterWithSelfAsTypeDeclaration.php
test/Integration/Methods/NoParameterWithContainerTypeDeclarationRuleTest.php

This PR
Follows #122 and https://github.com/phpstan/phpstan/issues/2430#issuecomment-531470927.

Fix: Resolve class name before attempting to analyze it

---

.dependabot/config.yml

This PR
Follows #122.
Related to #129.

Fix: Exclude zendframework/zend-servicemanager from automatic updates

---

CHANGELOG.md
src/Methods/FinalInAbstractClassRule.php
test/Fixture/Methods/FinalInAbstractClassRule/Success/InterfaceWithPublicMethod.php
test/Integration/Methods/FinalInAbstractClassRuleTest.php

This PR
Follows #123.
Fixes #131.

Fix: Exclude interfaces from analysis by Methods\FinalInAbstractClassRule

---

.php_cs.fixture
CHANGELOG.md
README.md
rules.neon
src/Methods/PrivateInFinalClassRule.php
test/Fixture/Methods/PrivateInFinalClassRule/Failure/AnonymousClassWithProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Failure/FinalClassWithProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/AbstractClassExtendingAbstractClassWithProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/AbstractClassWithProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/ClassWithProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/FinalClassWithPrivateMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/FinalClassWithProtectedMethodExtendingClassExtendingClassWithSameProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/FinalClassWithProtectedMethodExtendingClassWithSameProtectedMethod.php
test/Fixture/Methods/PrivateInFinalClassRule/Success/FinalClassWithPublicMethod.php
test/Integration/Methods/PrivateInFinalClassRuleTest.php

Enhancement: Implement Methods\PrivateInFinalClassRule

---

test/Integration/Classes/FinalRuleWithExcludedClassNamesTest.php
test/Integration/Methods/PrivateInFinalClassRuleTest.php
test/Integration/Statements/NoSwitchRuleTest.php

Fix: Keep cases sorted by key

---

.github/settings.yml

Fix: Stop waiting for builds for PHP 7.1 to complete

---

composer.json
composer.lock

This PR
💁‍♂ For reference, see https://github.com/phpstan/phpstan/releases/tag/0.12.0.

Enhancement: Allow installation with phpstan/phpstan:~0.12.0

---

.github/workflows/continuous-integration.yml
.php_cs.fixture

Fix: Run php-cs-fixer for fixtures

---

composer.json
composer.lock
test/AutoReview/SrcCodeTest.php
test/AutoReview/TestCodeTest.php

Enhancement: Use ergebnis/test-util instead of localheinz/test-util

---

.github/settings.yml
.github/workflows/continuous-integration.yml
composer.json
composer.lock

Enhancement: Run builds on PHP 7.4

---

CHANGELOG.md
phpstan.neon
rules.neon

Fix: Move parameters configuration into ergebnis scope

---

README.md

Fix: Update README.md in regard to parameter scope

---

Makefile

Fix: Use localheinz/composer-require-checker-action

---

CHANGELOG.md
src/Classes/FinalRule.php
test/Fixture/Classes/FinalRule/Success/NonFinalClassWithOrmMappingEntityAnnotationInInlineDocBlock.php
test/Fixture/Classes/FinalRule/Success/NonFinalClassWithOrmMappingEntityAnnotationInMultilineDocBlock.php
test/Integration/Classes/FinalRuleTest.php

Fix: Ignore entities with ORM\Mapping\Entity annotations in FinalRule

---

.php_cs.fixture
CHANGELOG.md
README.md
phpstan-baseline.neon
psalm-baseline.xml
rules.neon
src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
test/Fixture/Classes/PHPUnit/Framework/TestCaseWithSuffixRule/Failure/AbstractTestCase.php
test/Fixture/Classes/PHPUnit/Framework/TestCaseWithSuffixRule/Failure/ConcreteTestCaseExtendingAbstractTestCaseWithoutTestSuffix.php
test/Fixture/Classes/PHPUnit/Framework/TestCaseWithSuffixRule/Failure/ConcreteTestCaseWithoutTestSuffix.php
test/Fixture/Classes/PHPUnit/Framework/TestCaseWithSuffixRule/Success/ConcreteTestCaseWithSuffixTest.php
test/Fixture/Classes/PHPUnit/Framework/TestCaseWithSuffixRule/Success/ExplicitlyAbstractTestCase.php
test/Fixture/Classes/PHPUnit/Framework/TestCaseWithSuffixRule/Success/ImplicitlyAbstractTestCase.php
test/Integration/Classes/PHPUnit/Framework/TestCaseWithSuffixRuleTest.php

Enhancement: Implement Classes\PHPUnit\Framework\TestCaseWithSuffixRule

---

.github/dependabot.yml

Fix: Restore ignore rules

---

CHANGELOG.md

Fix: Formatting

---

CHANGELOG.md
src/Methods/FinalInAbstractClassRule.php
test/Fixture/Methods/FinalInAbstractClassRule/Success/AbstractClassWithNonFinalConstructor.php
test/Integration/Methods/FinalInAbstractClassRuleTest.php

Methods\FinalInAbstractClassRule: allow __construct method to be non-final

---

CHANGELOG.md
composer.json
composer.lock

This PR
Related to #285.
💁‍♂️ Will follow up with actually running builds on PHP 8.0 as well.

Enhancement: Allow installation with PHP 8.0

---

CHANGELOG.md
composer-require-checker.json
composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon
src/Classes/FinalRule.php
src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
src/Methods/NoParameterWithContainerTypeDeclarationRule.php
test/Integration/Classes/PHPUnit/Framework/TestCaseWithSuffixRuleTest.php
test/Integration/Methods/NoParameterWithContainerTypeDeclarationRuleTest.php

* Bump support for PHPStan to version 1.0
Fixes https://github.com/ergebnis/phpstan-rules/issues/379
These are the only deprecations I could find. `vendor/bin/phpstan` and `vendor/bin/phpunit test/` passed locally.
I hope I didn't miss anything that other tooling would catch 🤞

Bump support for PHPStan to version 1.0

---

Makefile
phpstan-baseline.neon

Fix: Use `--generate-baseline` option for generating baseline for `phpstan/phpstan`

---

.github/workflows/integrate.yaml

Fix: Do not bother caching cache files for `phpstan/phpstan` and `vimeo/psalm`

---

src/Classes/FinalRule.php
src/Classes/NoExtendsRule.php
src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
src/Closures/NoNullableReturnTypeDeclarationRule.php
src/Closures/NoParameterWithNullDefaultValueRule.php
src/Closures/NoParameterWithNullableTypeDeclarationRule.php
src/Expressions/NoCompactRule.php
src/Expressions/NoEmptyRule.php
src/Expressions/NoErrorSuppressionRule.php
src/Expressions/NoEvalRule.php
src/Expressions/NoIssetRule.php
src/Files/DeclareStrictTypesRule.php
src/Functions/NoNullableReturnTypeDeclarationRule.php
src/Functions/NoParameterWithNullDefaultValueRule.php
src/Functions/NoParameterWithNullableTypeDeclarationRule.php
src/Methods/FinalInAbstractClassRule.php
src/Methods/NoConstructorParameterWithDefaultValueRule.php
src/Methods/NoNullableReturnTypeDeclarationRule.php
src/Methods/NoParameterWithContainerTypeDeclarationRule.php
src/Methods/NoParameterWithNullDefaultValueRule.php
src/Methods/NoParameterWithNullableTypeDeclarationRule.php
src/Methods/PrivateInFinalClassRule.php
src/Statements/NoSwitchRule.php

Fix: Wrapping

---

.github/workflows/integrate.yaml
Makefile
src/Functions/NoNullableReturnTypeDeclarationRule.php

Fix: Split condition

---

.github/workflows/integrate.yaml
.php-cs-fixer.fixture.php
Makefile

Fix: Run `friendsofphp/php-cs-fixer` on fixtures

---

.github/workflows/integrate.yaml
CHANGELOG.md
Makefile
README.md
composer.json
composer.lock
psalm-baseline.xml
src/Classes/FinalRule.php
test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedDoctrineOrmMappingEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedOrmEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Failure/NonFinalClassWithUnqualifiedOrmMappingEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithAliasedOrmEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedDoctrineOrmMappingEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedMappingEntityAttribute.php
test/Fixture/Classes/FinalRuleWithAttributes/Success/NonFinalClassWithQualifiedOrmMappingEntityAttribute.php
test/Integration/Classes/FinalRuleWithAttributesTest.php

Fix: Adjust `Classes\FinalRule` to inspect attributes

---

README.md

This means a user can use the Copy button next to the code block on GitHub and paste the command into their terminal without getting an error.

Remove unnecessary shell input symbol from installation instructions

---

rules.neon

Since the rule has no configuration we can just move it under `rules:` right?

Simplify rules.neon

---

CHANGELOG.md
README.md
rules.neon
src/Methods/NoParameterWithContainerTypeDeclarationRule.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/ClassWithMethodWithParameterWithClassImplementingContainerInterfaceAsTypeDeclarationWhereNameIsExcluded.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/InterfaceWithMethodWithParameterWithContainerInterfaceAsTypeDeclarationWhereNameIsExcluded.php
test/Fixture/Methods/NoParameterWithContainerTypeDeclarationRule/Success/anonymous-class-with-method-with-parameter-with-class-implementing-container-interface-as-type-declaration-where-name-is-excluded.php
test/Integration/Methods/NoParameterWithContainerTypeDeclarationRuleTest.php

Enhancement: Allow configuring methods that are allowed to use container type declarations

---

phpstan-baseline.neon
phpstan.neon
test/Integration/AbstractTestCase.php

Fix: Remove deprecated `checkMissingIterableValueType` option

---

phpstan-baseline.neon
phpstan.neon

Fix: Remove deprecated `checkGenericClassInNonGenericObjectType` option

---

composer-require-checker.json
src/Classes/FinalRule.php
src/Classes/NoExtendsRule.php
src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
src/Closures/NoNullableReturnTypeDeclarationRule.php
src/Closures/NoParameterWithNullDefaultValueRule.php
src/Closures/NoParameterWithNullableTypeDeclarationRule.php
src/Expressions/NoCompactRule.php
src/Files/DeclareStrictTypesRule.php
src/Functions/NoNullableReturnTypeDeclarationRule.php
src/Functions/NoParameterWithNullDefaultValueRule.php
src/Functions/NoParameterWithNullableTypeDeclarationRule.php
src/Methods/FinalInAbstractClassRule.php
src/Methods/NoConstructorParameterWithDefaultValueRule.php
src/Methods/NoNullableReturnTypeDeclarationRule.php
src/Methods/NoParameterWithContainerTypeDeclarationRule.php
src/Methods/NoParameterWithNullDefaultValueRule.php
src/Methods/NoParameterWithNullableTypeDeclarationRule.php
src/Methods/PrivateInFinalClassRule.php

Fix: Remove conditions that should never evaluate to true

---

CHANGELOG.md
src/Methods/NoConstructorParameterWithDefaultValueRule.php

Follows #876.
Related to #873.

Fix: Return `RuleError` with identifier

---

.php-cs-fixer.fixture.php
CHANGELOG.md
src/Expressions/NoCompactRule.php
test/Fixture/Expressions/NoCompactRule/Failure/compact-used-with-incorrect-case.php

Fix: Adjust `NoCompactRule` to detect usages of `compact()` with incorrect case

---

CHANGELOG.md
src/Methods/PrivateInFinalClassRule.php
test/Integration/Methods/PrivateInFinalClassRuleTest.php

Fix: Use more appropriate message when detecting `protected` method in anonymous class

---

CHANGELOG.md
src/Methods/PrivateInFinalClassRule.php
test/Integration/Methods/PrivateInFinalClassRuleTest.php

Fix: Ignore `protected` methods declared in traits

---

CHANGELOG.md
composer-require-checker.json
src/Methods/PrivateInFinalClassRule.php
test/Fixture/Methods/PrivateInFinalClassRule/FinalClassWithProtectedMethodsWithPhpUnitAnnotations.php
test/Integration/Methods/PrivateInFinalClassRuleTest.php

Fix: Do not require methods with `phpunit/phpunit` annotations to be `private`

---

CHANGELOG.md
composer-require-checker.json
src/Analyzer.php
test/Integration/Closures/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Closures/NoParameterWithNullableTypeDeclarationRuleTest.php
test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Functions/NoParameterWithNullableTypeDeclarationRuleTest.php
test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php
test/Integration/Methods/NoParameterWithNullableTypeDeclarationRuleTest.php

Fix: Detect cases where `null` is referenced with incorrect case or relative to the root namespace

---

CHANGELOG.md
composer.json
composer.lock
phpstan-baseline.neon
src/Analyzer.php

Enhancement: Add support for `phpstan/phpstan:^2.0.0`

---

CHANGELOG.md
README.md
rules.neon
src/ErrorIdentifier.php
src/Functions/NoReturnByReferenceRule.php
src/Methods/NoReturnByReferenceRule.php
test/Fixture/Functions/NoReturnByReferenceRule/script.php
test/Fixture/Methods/NoReturnByReferenceRule/MethodInClass.php
test/Fixture/Methods/NoReturnByReferenceRule/MethodInClassReturningByReference.php
test/Fixture/Methods/NoReturnByReferenceRule/MethodInInterface.php
test/Fixture/Methods/NoReturnByReferenceRule/MethodInInterfaceReturningByReference.php
test/Fixture/Methods/NoReturnByReferenceRule/MethodInTrait.php
test/Fixture/Methods/NoReturnByReferenceRule/MethodInTraitReturningByReference.php
test/Fixture/Methods/NoReturnByReferenceRule/script.php
test/Integration/Functions/NoReturnByReferenceRuleTest.php
test/Integration/Methods/NoReturnByReferenceRuleTest.php
test/Unit/ErrorIdentifierTest.php

Enhancement: Implement `NoReturnByReferenceRule`

---

CHANGELOG.md
README.md
rules.neon

Enhancement: Extract `allRules` parameter to allow disabling and enabling all rules

---

CHANGELOG.md
README.md
composer-require-checker.json
rules.neon
src/ErrorIdentifier.php
src/Expressions/NoAssignByReferenceRule.php
test/Fixture/Expressions/NoAssignByReferenceRule/script.php
test/Integration/Expressions/NoAssignByReferenceRuleTest.php
test/Unit/ErrorIdentifierTest.php

Enhancement: Implement `NoAssignByReferenceRule`

---

phpstan-baseline.neon
src/Methods/InvokeParentHookMethodRule.php

Fix: Use `Invocation::never()`

---

.php-cs-fixer.fixture.php
CHANGELOG.md
composer-require-checker.json
src/Methods/InvokeParentHookMethodRule.php
test/Fixture/Methods/InvokeParentHookMethodRule/PHPUnit/Framework/ConcreteTestCaseInvokingNonEmptyParentHookMethodsInRightOrderWithCommentsTest.php

Fix: Ignore comments in `InvokeParentHookMethodRule`

---

CHANGELOG.md
src/CallLikes/NoNamedArgumentRule.php
test/Fixture/CallLikes/NoNamedArgumentRule/script.php
test/Integration/CallLikes/NoNamedArgumentRuleTest.php

Fix: Adjust `CallLikes\NoNamedArgumentRule` to handle `static` calls on variable expressions

---

CHANGELOG.md
src/CallLikes/NoNamedArgumentRule.php
test/Fixture/CallLikes/NoNamedArgumentRule/InvokableClass.php
test/Fixture/CallLikes/NoNamedArgumentRule/script.php
test/Integration/CallLikes/NoNamedArgumentRuleTest.php

Related to https://github.com/ergebnis/phpstan-rules/issues/946.

Fix: Adjust `CallLikes\NoNamedArgumentRule` to handle calls on invokables

---

.php-cs-fixer.fixture.php
CHANGELOG.md
composer-require-checker.json
src/CallLikes/NoNamedArgumentRule.php
test/Fixture/CallLikes/NoNamedArgumentRule/ClassUsingInvokableClass.php
test/Integration/CallLikes/NoNamedArgumentRuleTest.php

Fix: Adjust `CallLikes\NoNamedArgumentRule` to handle calls on callables assigned to properties

---

CHANGELOG.md
src/CallLikes/NoNamedArgumentRule.php
test/Fixture/CallLikes/NoNamedArgumentRule/ClassUsingInvokableClass.php
test/Fixture/CallLikes/NoNamedArgumentRule/script.php
test/Integration/CallLikes/NoNamedArgumentRuleTest.php

Fix: Adjust `CallLikes\NoNamedArgumentRule` to handle other calls with generic error message

---

CHANGELOG.md
src/CallLikes/NoNamedArgumentRule.php
test/Fixture/CallLikes/NoNamedArgumentRule/script.php
test/Integration/CallLikes/NoNamedArgumentRuleTest.php

Fix: Adjust `CallLikes\NoNamedArgumentRule` to handle calls to constructors of variable class names
