ergebnis/phpstan-rules

- test/AutoReview/SrcCodeTest.php
> Enhancement: Assert that source classes have integration tests

- CHANGELOG.md
- README.md
- src/Classes/AbstractOrFinalRule.php
- src/Classes/FinalRule.php
- test/AutoReview/TestCodeTest.php
- test/Fixture/Classes/AbstractOrFinalRule/NeitherAbstractNorFinalClassButWhitelisted.php
- test/Fixture/Classes/FinalRule/NeitherAbstractNorFinalClassButWhitelisted.php
- test/Integration/Classes/AbstractOrFinalRuleTest.php
- test/Integration/Classes/FinalRuleTest.php
- test/Unit/Classes/AbstractOrFinalRuleTest.php
- test/Unit/Classes/FinalRuleTest.php
This PR
Follows https://twitter.com/marcospassos/status/1062887609062567936.
/cc @marcospassos
> Enhancement: Allow whitelisting of classes

- test/AutoReview/TestCodeTest.php
- test/Integration/AbstractTestCase.php
- test/Integration/Classes/AbstractOrFinalRuleTest.php
- test/Integration/Classes/FinalRuleTest.php
- test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php
> Enhancement: Extract abstract rule test case

- composer.json
> Enhancement: Add phpstan-extreme-rules as keyword

- README.md
> Fix: Clean up README.md

- CHANGELOG.md
- README.md
> Enhancement: Further improve README.md

- CHANGELOG.md
- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see 
* https://github.com/phpstan/phpstan/releases/tag/0.11
* https://github.com/phpstan/phpstan-deprecation-rules/releases/tag/0.11
* https://github.com/phpstan/phpstan-strict-rules/releases/tag/0.11
> Enhancement: Allow installation of phpstan/phpstan:~0.11.0

- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://github.com/localheinz/composer-normalize/compare/1.1.0...1.1.1.
> Fix: Update localheinz/composer-normalize

- test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
> Fix: Remove duplicate dashes

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
> Enhancement: Allow usage with phpstan/extension-installer

- .dependabot/config.yml
- .gitattributes
> Enhancement: Add basic configuration for dependabot

- composer.json
- composer.lock
This PR
Blocks #79.
💁‍♂ For reference, see https://github.com/nikic/PHP-Parser/compare/v4.1.0...v4.2.3.
> Enhancement: Require nikic/php-parser:^4.2.3

- .github/workflows/stale.yml
- Makefile
> Enhancement: Synchronize project tooling configuration with localheinz/php-library-template

- composer.json
- composer.lock
This PR
Blocks #79.
💁‍♂ For reference, see https://github.com/phpstan/phpstan/compare/0.11.7...0.11.15.
> Enhancement: Require phpstan/phpstan:~0.11.7

- CHANGELOG.md
> Fix: Version

- .github/workflows/continuous-integration.yml
- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Drop support for PHP 7.1

- .dependabot/config.yml
- .github/CONTRIBUTING.md
- .github/settings.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/stale.yml
- Makefile
- composer.json
- composer.lock
- phpstan-baseline.neon
- phpstan.neon
> Enhancement: Synchronize project tooling configuration with ergebnis/php-library-template

- .github/workflows/continuous-integration.yml
- .php_cs
- .php_cs.fixture
- Makefile
- README.md
- phpstan.neon
- test/Unit/phpunit.xml
> Enhancement: Synchronize with ergebnis/php-library-template

- test/Integration/AbstractTestCase.php
- test/Integration/Classes/FinalRuleTest.php
- test/Integration/Classes/FinalRuleWithAbstractClassesAllowedTest.php
- test/Integration/Classes/FinalRuleWithExcludedClassNamesTest.php
- test/Integration/Classes/NoExtendsRuleTest.php
- test/Integration/Classes/NoExtendsRuleWithClassesAllowedToBeExtendedTest.php
- test/Integration/Closures/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Closures/NoParameterWithNullDefaultValueRuleTest.php
- test/Integration/Closures/NoParameterWithNullableTypeDeclarationRuleTest.php
- test/Integration/Expressions/NoCompactRuleTest.php
- test/Integration/Expressions/NoEmptyRuleTest.php
- test/Integration/Expressions/NoErrorSuppressionRuleTest.php
- test/Integration/Expressions/NoEvalRuleTest.php
- test/Integration/Expressions/NoIssetRuleTest.php
- test/Integration/Files/DeclareStrictTypesRuleTest.php
- test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Functions/NoParameterWithNullDefaultValueRuleTest.php
- test/Integration/Functions/NoParameterWithNullableTypeDeclarationRuleTest.php
- test/Integration/Methods/FinalInAbstractClassRuleTest.php
- test/Integration/Methods/NoConstructorParameterWithDefaultValueRuleTest.php
- test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Methods/NoParameterWithContainerTypeDeclarationRuleTest.php
- test/Integration/Methods/NoParameterWithNullDefaultValueRuleTest.php
- test/Integration/Methods/NoParameterWithNullableTypeDeclarationRuleTest.php
- test/Integration/Methods/PrivateInFinalClassRuleTest.php
- test/Integration/Statements/NoSwitchRuleTest.php
> Fix: Rename data providers

- .github/workflows/triage.yaml
> Fix: Adjust usage of octokit

- composer.json
- composer.lock
- psalm-baseline.xml
> Enhancement: Update `vimeo/psalm`

- src/Classes/FinalRule.php
> Fix: Split condition

- .github/settings.yml
- .github/workflows/integrate.yaml
> Enhancement: Run tests on PHP 8.0

- psalm-baseline.xml
- src/Classes/FinalRule.php
- src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
> Fix: DocBlocks

- psalm-baseline.xml
- src/Classes/FinalRule.php
> Fix: Avoid comparing boolean with boolean

- README.md
Fixes a broken anchor link in the README.md
> README.md: Fix broken anchor link

- .github/settings.yml
- .github/workflows/integrate.yaml
- CHANGELOG.md
- composer.json
- composer.lock
> Enhancement: Add support for PHP 8.2

- CHANGELOG.md
- README.md
- phpstan.neon
- rules.neon
> Enhancement: Allow disabling rules

- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/renew.yaml
- .php-cs-fixer.fixture.php
- .php-cs-fixer.php
- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Drop support for PHP 8.0

- .github/settings.yml
- .github/workflows/integrate.yaml
- CHANGELOG.md
- composer.json
- composer.lock
This pull request adds PHP 8.3 support to this package.
> Adds PHP 8.3 support

- .editorconfig
- .github/SECURITY.md
- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/merge.yaml
- .github/workflows/release.yaml
- .github/workflows/renew.yaml
- .github/workflows/triage.yaml
- .phive/phars.xml
> Enhancement: Synchronize with `ergebnis/php-package-template`

- test/Fixture/Methods/PrivateInFinalClassRule/Success/FinalClassWithProtectedMethodFromTrait.php
- test/Fixture/Methods/PrivateInFinalClassRule/Success/TraitWithProtectedMethod.php
- test/Integration/Methods/PrivateInFinalClassRuleTest.php
> Fix: Add test case

- .github/workflows/integrate.yaml
- CHANGELOG.md
- composer.json
- composer.lock
> Enhancement: Allow installation of `nikic/php-parser:^5.0.0`

- rules.neon
- src/Analyzer.php
- src/Closures/NoNullableReturnTypeDeclarationRule.php
- src/Closures/NoParameterWithNullDefaultValueRule.php
- src/Closures/NoParameterWithNullableTypeDeclarationRule.php
- src/Functions/NoNullableReturnTypeDeclarationRule.php
- src/Functions/NoParameterWithNullDefaultValueRule.php
- src/Functions/NoParameterWithNullableTypeDeclarationRule.php
- src/Methods/NoNullableReturnTypeDeclarationRule.php
- src/Methods/NoParameterWithNullDefaultValueRule.php
- src/Methods/NoParameterWithNullableTypeDeclarationRule.php
- test/Integration/Closures/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Closures/NoParameterWithNullDefaultValueRuleTest.php
- test/Integration/Closures/NoParameterWithNullableTypeDeclarationRuleTest.php
- test/Integration/Functions/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Functions/NoParameterWithNullDefaultValueRuleTest.php
- test/Integration/Functions/NoParameterWithNullableTypeDeclarationRuleTest.php
- test/Integration/Methods/NoNullableReturnTypeDeclarationRuleTest.php
- test/Integration/Methods/NoParameterWithNullDefaultValueRuleTest.php
- test/Integration/Methods/NoParameterWithNullableTypeDeclarationRuleTest.php
> Enhancement: Extract `Analyzer`

- composer.json
- composer.lock
- src/Classes/FinalRule.php
- src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
> Fix: Remove `nikic/php-parser`

- CHANGELOG.md
- composer.json
- composer.lock
- src/Classes/PHPUnit/Framework/TestCaseWithSuffixRule.php
> Enhancement: Require `phpstan/phpstan:^2.1.8`
